version: "3.7"

services:
  webserver:
    privileged: true
    build: 
      context: docker/d2d_php/
      dockerfile: Dockerfile
    ports: 
      - 8888:80
    container_name: d2d
    restart: always
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./src/:/var/www/html/
      - ./log/:/var/log/httpd/
    networks:
      d2d_network:
        aliases: 
          - d2d_host
        ipv4_address: 172.25.0.5

  mysql:
    image: mariadb:10
    container_name: d2ddb
    ports: 
      - 3309:3306
    volumes: 
      - ./mysql-data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=Kb.204.h3      
    networks:
      d2d_network:
        aliases: 
          - d2d_db
        ipv4_address: 172.25.0.4
  phpmysadmin:
    image: phpmyadmin/phpmyadmin
    container_name: d2d_phpmyadmin   
    links: 
        - mysql:mysql
    ports:
        - 8088:80
    environment:     
      - PMA_HOST=mysql
      - PMA_PORT=3307
      - PMA_USER=root
      - PMA_PASSWORD=Kb.204.h3
          

    networks:
      d2d_network:
        aliases: 
          - phpmyadmin_db
        ipv4_address: 172.25.0.6

volumes:
  html: {}
  mysql: {}

networks:
  d2d_network:
    name: d2d
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: 172.25.0.0/24